[package]
name = "anagram_sleuth"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.74"
flate2 = "1.0"
regex = "1"

[dev-dependencies]
wasm-bindgen-test = "0.2"